services:
  cfg1:
    image: mongo:7
    container_name: cfg1
    command: >
      mongod
      --configsvr
      --replSet cfgRS
      --port 27017
      --bind_ip_all
      --keyFile /etc/mongo-keyfile
    networks:
      - mongo-cluster
    volumes:
      - cfg1_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

  shard1:
    image: mongo:7
    container_name: shard1
    command: >
      mongod
      --shardsvr
      --replSet shard1RS
      --port 27017
      --bind_ip_all
      --keyFile /etc/mongo-keyfile
    networks:
      - mongo-cluster
    volumes:
      - shard1_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

  shard2:
    image: mongo:7
    container_name: shard2
    command: >
      mongod
      --shardsvr
      --replSet shard2RS
      --port 27017
      --bind_ip_all
      --keyFile /etc/mongo-keyfile
    networks:
      - mongo-cluster
    volumes:
      - shard2_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

  mongos:
    image: mongo:7
    container_name: mongos
    depends_on:
      - cfg1
      - shard1
      - shard2
    command: >
      mongos
      --configdb cfgRS/cfg1:27017
      --port 27017
      --bind_ip_all
      --keyFile /etc/mongo-keyfile
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

networks:
  mongo-cluster:

volumes:
  cfg1_data:
  shard1_data:
  shard2_data:
